#################################################
# Dockerfile to build mongodb and start db on server
# Based on oficial mongo Dockerfile
#################################################

FROM mongo

MAINTAINER Rodrigo Seiji Piubeli Hirao <rodrigo.seiji.hirao@gmail.com>

# We do nothing apart from what mongo already do
# So we will use docker native mongo dockerfile instead
# look at `deploy.sh`