#################################################
# Dockerfile to build mongodb and start db on server
# Based on oficial mongo Dockerfile
#################################################

FROM mongo

MAINTAINER Rodrigo Seiji Piubeli Hirao <rodrigo.seiji.hirao@gmail.com>

USER discipuluz+core